# Generated by Django 5.2.12 on 2026-08-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'مدير النظام'), ('dept_manager', 'مدير القسم'), ('manager', 'مدير العمليات'), ('representative', 'المندوب'), ('receiver', 'المستلم'), ('accountant', 'المحاسب'), ('data', 'البيانات')], default='representative', max_length=20, verbose_name='الدور'),
        ),
    ]
