# Generated by Django 5.2.12 on 2026-08-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expand_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='رقم دولي بدون + مثل 9665xxxxxxxx', max_length=20, verbose_name='واتساب'),
        ),
    ]
