# Generated by Django 5.2.12 on 2026-08-20 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=255, verbose_name='العنصر')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('reason', models.TextField(verbose_name='سبب الإرجاع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'تم القبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_return_requests', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('representative', models.ForeignKey(limit_choices_to={'role': 'representative'}, on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='المندوب')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_return_requests', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
            ],
            options={
                'verbose_name': 'مرتجع',
                'verbose_name_plural': 'المرتجعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=255, verbose_name='العنصر')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='التاريخ المتوقع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='السعر')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_supply_orders', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('representative', models.ForeignKey(limit_choices_to={'role': 'representative'}, on_delete=django.db.models.deletion.PROTECT, related_name='supply_orders', to=settings.AUTH_USER_MODEL, verbose_name='المندوب')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_supply_orders', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
            ],
            options={
                'verbose_name': 'طلب توريد',
                'verbose_name_plural': 'طلبات التوريد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('urgent', 'عاجل'), ('medium', 'متوسط'), ('normal', 'عادي')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('todo', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('done', 'مكتمل')], default='todo', max_length=20, verbose_name='الحالة')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='الموعد')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='التقدم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='معيّن إلى')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['-created_at'],
            },
        ),
    ]
