# Generated by Django 5.2.12 on 2026-08-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_relax_return_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='sku',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='item_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الصنف'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='package',
            field=models.CharField(blank=True, max_length=100, verbose_name='العبوة'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
    ]
