# Generated by Django 5.2.12 on 2026-08-20 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_return_item_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyorder',
            name='item_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الصنف'),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='package',
            field=models.CharField(blank=True, max_length=100, verbose_name='العبوة'),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_orders', to=settings.AUTH_USER_MODEL, verbose_name='المندوب'),
        ),
    ]
