# Generated by Django 5.2.12 on 2026-08-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_supply_item_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('item_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الصنف')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('package', models.CharField(blank=True, max_length=100, verbose_name='العبوة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
                'ordering': ['name'],
            },
        ),
    ]
