# Generated by Django 5.2.12 on 2026-08-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_catalog_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='return_type',
            field=models.CharField(choices=[('unacceptable', 'غير مقبول'), ('exchange', 'تبديل'), ('return', 'مرتجع')], default='return', max_length=20, verbose_name='نوع المرتجع'),
        ),
    ]
