# Generated by Django 5.2.12 on 2026-08-20 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_return_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='rep_decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ قرار المندوب'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='rep_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_decided_returns', to=settings.AUTH_USER_MODEL, verbose_name='عمّده / رفضه'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='rep_decision',
            field=models.CharField(choices=[('pending', 'بانتظار التعميد'), ('authorized', 'معتمد'), ('rejected', 'مرفوض من المندوب')], default='pending', max_length=20, verbose_name='تعميد المندوب'),
        ),
    ]
