# Generated by Django 5.2.12 on 2026-08-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_return_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.CharField(blank=True, max_length=150, verbose_name='موقع الفرع'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز'),
        ),
        migrations.AddField(
            model_name='task',
            name='public_token',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True, verbose_name='رمز الرابط'),
        ),
        migrations.AddField(
            model_name='task',
            name='visit_details',
            field=models.TextField(blank=True, verbose_name='تفاصيل الزيارة'),
        ),
    ]
