# Generated by Django 5.2.12 on 2026-08-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_task_visit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppRoleContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system_admin', 'مدير النظام'), ('dept_manager', 'مدير القسم'), ('manager', 'مدير العمليات'), ('representative', 'المندوب'), ('receiver', 'المستلم'), ('accountant', 'المحاسب'), ('data', 'البيانات')], max_length=20, unique=True, verbose_name='الدور')),
                ('phone', models.CharField(blank=True, help_text='صيغة دولية بدون + مثل 9665xxxxxxxx', max_length=20, verbose_name='رقم واتساب')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رقم واتساب للدور',
                'verbose_name_plural': 'أرقام واتساب للأدوار',
                'ordering': ['role'],
            },
        ),
    ]
