# Generated by Django 5.2.12 on 2026-08-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0026_batch_public_tokens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyorder',
            options={'verbose_name_plural': 'طلبات التوريد'},
        ),
    ]
