# Generated by Django 5.2.12 on 2026-08-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_alter_supplyorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyorder',
            name='package',
            field=models.CharField(blank=True, max_length=50, verbose_name='العبوة'),
        ),
    ]
