# Generated by Django 5.2.12 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0028_dailyorder_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='item_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='رقم الصنف'),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(
                fields=('name', 'package'),
                name='ops_catalogitem_name_package_uniq',
            ),
        ),
    ]
