# Generated by Django 5.2.12 on 2026-08-22

from django.db import migrations, models


def merge_catalog_by_name(apps, schema_editor):
    CatalogItem = apps.get_model('ops', 'CatalogItem')
    grouped = {}
    for item in CatalogItem.objects.all().order_by('pk'):
        grouped.setdefault(item.name, []).append(item)

    for items in grouped.values():
        if len(items) <= 1:
            continue
        keeper = items[0]
        units = []
        for it in items:
            for value in (it.unit, it.package):
                value = (value or '').strip()
                if not value:
                    continue
                for chunk in value.replace('،', ',').split(','):
                    unit = chunk.strip()
                    if unit and unit not in units:
                        units.append(unit)
        keeper.unit = '، '.join(units)
        keeper.package = ''
        keeper.save(update_fields=['unit', 'package'])
        for duplicate in items[1:]:
            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0029_catalogitem_name_package'),
    ]

    operations = [
        migrations.RunPython(merge_catalog_by_name, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='catalogitem',
            name='ops_catalogitem_name_package_uniq',
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='unit',
            field=models.CharField(
                blank=True,
                help_text='يمكن إدخال أكثر من وحدة مفصولة بفاصلة (مثل: جرم، كيس، كرتون)',
                max_length=500,
                verbose_name='الوحدة',
            ),
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(
                fields=('name',),
                name='ops_catalogitem_name_uniq',
            ),
        ),
    ]
