# Generated by Django 5.2.12 on 2026-08-23 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0030_catalogitem_unique_name_multi_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='رقم الملف')),
                ('item_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الصنف')),
                ('item_name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('package', models.CharField(blank=True, max_length=100, verbose_name='العبوة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_offer_items', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'صنف عرض',
                'verbose_name_plural': 'أصناف العروض',
                'ordering': ['-created_at', 'pk'],
            },
        ),
    ]
