# Generated by Django 5.2.12 on 2026-08-23 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0031_offeritem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offeritem',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='رمز PDF'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_offer_items', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
