# Generated by Django 5.2.12 on 2026-09-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0033_offeritem_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='item_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='رقم الصنف / الباركود'),
        ),
    ]
