# Generated by Django 5.2.12 on 2026-09-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0036_seed_accounting_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costsettlement',
            name='accounting_account',
        ),
        migrations.RemoveField(
            model_name='costsettlement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='costsettlementline',
            name='settlement',
        ),
        migrations.DeleteModel(
            name='AccountingAccount',
        ),
        migrations.DeleteModel(
            name='CostSettlement',
        ),
        migrations.DeleteModel(
            name='CostSettlementLine',
        ),
    ]
