# Generated by Django 5.2.12 on 2026-09-19 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0037_remove_cost_settlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='رمز الحساب')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'حساب محاسبي',
                'verbose_name_plural': 'الحسابات المحاسبية',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('code',), name='ops_accountingaccount_code_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CostSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الملف')),
                ('branch', models.CharField(blank=True, max_length=150, verbose_name='الفرع')),
                ('settlement_date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('entry_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الدخول')),
                ('vehicle_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='السيارة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'معتمد'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='ops.accountingaccount', verbose_name='الحساب المحاسبي')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cost_settlements', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'تسوية تكاليف',
                'verbose_name_plural': 'تسويات التكاليف',
                'ordering': ['-settlement_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CostSettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='الصنف')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='العدد')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='السعر')),
                ('column_side', models.CharField(choices=[('right', 'يمين'), ('left', 'يسار')], default='right', max_length=10, verbose_name='العمود')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ops.costsettlement', verbose_name='ملف التسوية')),
            ],
            options={
                'verbose_name': 'صنف تسوية',
                'verbose_name_plural': 'أصناف التسوية',
                'ordering': ['column_side', 'sort_order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='costsettlement',
            index=models.Index(fields=['settlement_date', 'status'], name='ops_costset_settlem_5cb426_idx'),
        ),
        migrations.AddIndex(
            model_name='costsettlementline',
            index=models.Index(fields=['settlement', 'column_side', 'sort_order'], name='ops_costset_settlem_0fd2d3_idx'),
        ),
    ]
