# Generated by Django 5.2.12 on 2026-09-23 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0039_costsettlement_public_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysupplydistribution',
            name='source_cost_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='ops.costsettlement', verbose_name='طلب السوق المصدر'),
        ),
        migrations.AddField(
            model_name='dailysupplydistribution',
            name='source_settlement_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='ops.costsettlementline', verbose_name='سطر طلب السوق'),
        ),
        migrations.AddIndex(
            model_name='dailysupplydistribution',
            index=models.Index(fields=['source_cost_settlement', 'source_settlement_line'], name='ops_dailysu_source__788b3b_idx'),
        ),
    ]
