from django.urls import path

from . import views

app_name = 'ops'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('supply/', views.supply_list, name='supply'),
    path('supply/create/', views.supply_create, name='supply_create'),
    path('supply/<int:pk>/', views.supply_detail, name='supply_detail'),
    path('supply/<int:pk>/complete/', views.supply_complete, name='supply_complete'),
    path('supply/<int:pk>/reject/', views.supply_reject, name='supply_reject'),
    path('supply/<int:pk>/delete/', views.supply_batch_delete, name='supply_batch_delete'),
    path('supply/<int:pk>/pdf/', views.supply_batch_pdf, name='supply_batch_pdf'),
    path('distribution/', views.daily_distribution_list, name='daily_distribution'),
    path('distribution/create/', views.daily_distribution_create, name='daily_distribution_create'),
    path('distribution/<int:pk>/delete/', views.daily_distribution_delete, name='daily_distribution_delete'),
    path('returns/', views.returns_list, name='returns'),
    path('returns/create/', views.return_create, name='return_create'),
    path('returns/batch/<int:pk>/pdf/', views.return_batch_pdf, name='return_batch_pdf'),
    path('returns/batch/<int:pk>/delete/', views.return_batch_delete, name='return_batch_delete'),
    path('returns/p/<str:token>/pdf/', views.return_batch_pdf_public, name='return_batch_pdf_public'),
    path('returns/p/<str:token>/document.pdf', views.return_batch_pdf_public, name='return_batch_pdf_public_file'),
    path('returns/items/<int:pk>/update/', views.return_item_update, name='return_item_update'),
    path('returns/<int:pk>/authorize/', views.return_rep_authorize, name='return_authorize'),
    path('returns/<int:pk>/rep-reject/', views.return_rep_reject, name='return_rep_reject'),
    path('returns/<int:pk>/accept/', views.return_accept, name='return_accept'),
    path('returns/<int:pk>/reject/', views.return_reject, name='return_reject'),
    path('orders/', views.daily_orders_list, name='daily_orders'),
    path('orders/create/', views.daily_order_create, name='daily_order_create'),
    path('orders/compare/', views.price_compare, name='price_compare'),
    path('orders/<int:pk>/approve/', views.daily_order_approve, name='daily_order_approve'),
    path('orders/<int:pk>/reject/', views.daily_order_reject, name='daily_order_reject'),
    path('orders/<int:pk>/pdf/', views.daily_order_batch_pdf, name='daily_order_batch_pdf'),
    path('orders/<int:pk>/delete/', views.daily_order_delete, name='daily_order_delete'),
    path('orders/p/<str:token>/pdf/', views.daily_order_pdf_public, name='daily_order_pdf_public'),
    path('orders/p/<str:token>/document.pdf', views.daily_order_pdf_public, name='daily_order_pdf_public_file'),
    path('tasks/', views.tasks_board, name='tasks'),
    path('tasks/create/', views.task_create, name='task_create'),
    path('tasks/<int:pk>/move/', views.task_move, name='task_move'),
    path('tasks/<int:pk>/review/', views.task_review, name='task_review'),
    path('tasks/p/<str:token>/', views.task_public, name='task_public'),
    path('items/', views.items_list, name='items'),
    path('items/create/', views.item_create, name='item_create'),
    path('items/<int:pk>/delete/', views.item_delete, name='item_delete'),
    path('items/import/', views.items_import_excel, name='items_import'),
    path('items/template/', views.items_template_download, name='items_template'),
    path('settings/', views.settings_view, name='settings'),
    path('branches/', views.branches_setup, name='branches'),
    path('suppliers/', views.suppliers_setup, name='suppliers'),
    path('whatsapp/', views.whatsapp_hub, name='whatsapp'),
    path('whatsapp/api/qr/', views.whatsapp_qr_api, name='whatsapp_qr'),
    path('whatsapp/api/status/', views.whatsapp_status_api, name='whatsapp_status'),
    path('whatsapp/api/logout/', views.whatsapp_logout_api, name='whatsapp_logout'),
    path('whatsapp/api/recreate/', views.whatsapp_recreate_api, name='whatsapp_recreate'),
    path('whatsapp/api/test/', views.whatsapp_test_api, name='whatsapp_test'),
]
